import { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { SideBarNav } from '@/components/custom-ui/reuseables';
import React from 'react';
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({
  children,
}: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen overflow-hidden">
          {/* Sidebar fixed on the left */}
          <SideBarNav />
          
          {/* Main content area */}
            <div className="flex-1 flex flex-col ml-64">

            <main className="flex-1 p-4 md:p-6 overflow-y-auto">
              
                {children}
             
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
